name: Show PR Description

on:
  workflow_dispatch:
    inputs:
      pr_id:
        description: "Pull Request ID"
        required: true
        type: string

jobs:
  fetch-pr-details:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Fetch PR details
      id: fetch-pr
      run: |
        PR_ID=${{ inputs.pr_id }}
        PR_DETAILS=$(gh pr view $PR_ID --json body | jq '.')
        echo "PR_BODY<<EOF" >> $GITHUB_ENV
        echo "$(echo $PR_DETAILS | jq -r '.body')" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    
    - name: Display PR details
      run: |
        echo "Pull Request Description: ${{ env.PR_BODY }}"
      
